apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  DB_HOST: "10.100.94.138"
  DB_PORT: "5432"
  DB_USERNAME: "myuser"
  DB_NAME: "mydatabase"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==
