apiVersion: v1
kind: Service
metadata:
  name: prj4-api
spec:
  type: LoadBalancer
  selector:
    service: prj4-api
  ports:
    - name: "5153"
      protocol: TCP
      port: 5153
      targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prj4-api
  labels:
    name: prj4-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: prj4-api
  template:
    metadata:
      labels:
        service: prj4-api
    spec:
      containers:
        - name: prj4-api
          image: 535172493685.dkr.ecr.us-east-1.amazonaws.com/prj4:0.0.1
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          envFrom:
            - secretRef:
                name: db-password
            - configMapRef:
                name: db-configmap
      restartPolicy: Always
